### ISSUE TITLE
User can set a saved list of criteria / standards as an "option." 

### ISSUE THREAD

**Issue by bryan-jun** [bryan-jun/final-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can fill in various components of an option (list) and save it for future viewing. 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Users will go down a list of questions / form components and fill in or choose from drop-downs where applicable to customize a set of criteria / standards that determine what kind of restaurants they'll be shown with the option clicked.  

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/61750728/177900369-3464e099-78cc-441f-9a3b-71e01362622e.png)
![image](https://user-images.githubusercontent.com/61750728/177900390-a301d7fb-3abe-4385-8ae3-097b58821f1d.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Create table in `schema.sql` under "public"."options" with listId (integer), listName (text), distance (integer), priceTag (integer), cuisine (text), open (boolean), buttonColor (text), favorite (boolean), createdAt (timestamp) 
- [x] Update `data.sql` to update each column with whatever is inputted by the user 

### ☁️ Server

- [x] Update `server/index.js` to enable the ability to post to options table the various fields filled out by the user 
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a component to render the form for fill out options 
- [x] Create a component for the top menu bar
- [ ] Create a component for button preview (Desktop only) 

### 🧑‍⚕️ Clean Up

- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
