### ISSUE TITLE
User can load previously saved options

### ISSUE THREAD

**Issue by bryan-jun** [bryan-jun/final-project#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can load and view previously saved options. 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will be able to go to the home page and view all the options they've saved prior. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/61750728/177901498-6fcf27d2-f19f-4ea7-bbef-621f75880e2f.png)
![image](https://user-images.githubusercontent.com/61750728/177901525-49ae5c62-37db-4f03-bea8-3c76d30c5478.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [ ] Update `server/index.js` to enable get calls to pull information from the options table, specifically the listName and buttonColor 
- [ ] Test with HTTPie
- [ ] Handle all errors and respond to the client

### ⚡ Client

- [ ] Create a component for buttons that generates based on the number of options available in the database, pulled via the server 
- [ ] Update menu bar component to show home page menu bar
- [ ] Create home page component to house the buttons and account for as many or as little buttons as possible

### 🧑‍⚕️ Clean Up

- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
